name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

  build:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: app/**/*.apk