name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: app/**/*.apk